### ISSUE TITLE
Add links to example presentations on homepage

### ISSUE THREAD

**Issue by drnic** [juliocesar/shining#1]

**Comment by juliocesar** [comment]
There was one! It got taken out right before I added preloading. Under really slow connections it would crap the whole thing out.

I'll re-add today.

**Comment by juliocesar** [comment]
Done. I think for now it kills the need for a quick example. I'll add a proper walk through all the features example later, as right now I desperately need to update the project's page to reflect everything that changed on 1.3.0.

http://shining.heroku.com/example/index.html
