### ISSUE TITLE
The Fat Slide Box Location issue in Safari

### ISSUE THREAD

**Issue by mccrory** [juliocesar/shining#2]
When transitioning from the slide BEFORE the Fat Slide, the Fat Slide Box is shifted to the right.  If you proceed to the slide AFTER the Fat Slide and then go Back to the Fat Slide, the Fat Slide Box is correctly positioned.  This bug/quirk is repeatable.

**Comment by mccrory** [comment]
Just trying to help out....this project has LOTS of potential!

**Comment by juliocesar** [comment]
No worries! I'm aware of the issue and I agree it needs to be fixed. The transition isn't "smart". It has no awareness as to whether it's moving backwards or forwards. So I'll tackle it from that perspective.

Thanks!
