### ISSUE TITLE
is not a Shining presentation!

### ISSUE THREAD

**Issue by clm-a** [juliocesar/shining#3]
Hey !
Maybe I did something wrong but now I get the issue :
..... is not a Shining presentation! (backtrace below)

I can't remember any particular alteration.
I just slightly modified config.ru and put the preso under Git, in order to deploy it to Heroku (which has worked very well).

What could raise such an exception ?

$ cd myPres
$ shine slide myslide
/usr/local/lib/ruby19/gems/1.9/gems/shining-1.3.1/lib/shining/preso.rb:28:in `rescue in open': /usr/home/clement/myPres is not a Shining presentation! (RuntimeError)
    from /usr/local/lib/ruby19/gems/1.9/gems/shining-1.3.1/lib/shining/preso.rb:25:in`open'
    from /usr/local/lib/ruby19/gems/1.9/gems/shining-1.3.1/bin/shine:46:in `new_slide!'
    from /usr/local/lib/ruby19/gems/1.9/gems/shining-1.3.1/bin/shine:24:in`figure_what_to_do!'
    from /usr/local/lib/ruby19/gems/1.9/gems/shining-1.3.1/bin/shine:66:in `<top (required)>'
    from /usr/local/bin/shine:19:in`load'
    from /usr/local/bin/shine:19:in `<main>'

**Comment by juliocesar** [comment]
Since it's an existing presentation and you're just creating a new slide, I'm guessing it's something malformed in the config.json file. I'm more than happy to have a look for you if you send me your presentation dir. Feel free to mail it to me directly at julioody (at) gmail dot com

**Comment by clm-a** [comment]
Totally right !
I was looking for a missing file or so -- but indeed that was an extra comma in the JSON slides list in config.ru
{
  "slides":       [
        "welcome",
        "intro", // <-- here :-s
       ],
  "title":        "Your presentation",
  "plugins":      ["resize", "syntaxhighlighter"],
  "transitions":  "fade"
}

Sure my fault ;)
Thx a lot !
