### ISSUE TITLE
Cross Browser Compatibiliy: Mutiple JS Errors when using Internet Explorer

### ISSUE THREAD

**Issue by natshergold** [juliocesar/shining#4]
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; OfficeLiveConnector.1.4; OfficeLivePatch.1.3; AskTB5.6)
Timestamp: Thu, 17 Jun 2010 05:08:49 UTC

Message: 'Haml' is null or not an object
Line: 260
Char: 9
Code: 0
URI: http://sydjs-architecting.heroku.com/vendor/lib/shining.js

Message: 'Haml' is null or not an object
Line: 260
Char: 9
Code: 0
URI: http://sydjs-architecting.heroku.com/vendor/lib/shining.js

Message: 'Haml' is null or not an object
Line: 260
Char: 9
Code: 0
URI: http://sydjs-architecting.heroku.com/vendor/lib/shining.js

Message: 'Haml' is null or not an object
Line: 260
Char: 9
Code: 0
URI: http://sydjs-architecting.heroku.com/vendor/lib/shining.js

**Comment by juliocesar** [comment]
Ok, fixed. haml-js (http://github.com/creationix/haml-js) doesn't work with IE8. I'm using my own fork, which I tested it and it works fine. Thanks!
