### ISSUE TITLE
Cross Browser Compatibiliy: When using firefox code samples fail to display

### ISSUE THREAD

**Issue by natshergold** [juliocesar/shining#5]
I get the following error in my firebug console but it may be unrelated.

console is not defined
[Break on this error] console.log(slidePlusExtension(name, 'css'))

**Comment by natshergold** [comment]
Sorry Should have included the version:

Firefox Version 3.6.3

Mozilla/5.0 (Windows; U; Windows NT 6.1; en-GB; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3

**Comment by juliocesar** [comment]
Yeah... massive overlook. Fixed and closed.
